package com.backend.Domain;

import java.io.Serializable;
import java.util.Date;

public class Markrecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column markrecord.RID
     *
     * @mbggenerated
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column markrecord.subjID
     *
     * @mbggenerated
     */
    private Integer subjid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column markrecord.practiScore
     *
     * @mbggenerated
     */
    private Float practiscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column markrecord.theoryScore
     *
     * @mbggenerated
     */
    private Float theoryscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column markrecord.diffiScore
     *
     * @mbggenerated
     */
    private Float diffiscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column markrecord.comUID
     *
     * @mbggenerated
     */
    private Integer comuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column markrecord.lastTime
     *
     * @mbggenerated
     */
    private Date lasttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column markrecord.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column markrecord.RID
     *
     * @return the value of markrecord.RID
     *
     * @mbggenerated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column markrecord.RID
     *
     * @param rid the value for markrecord.RID
     *
     * @mbggenerated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column markrecord.subjID
     *
     * @return the value of markrecord.subjID
     *
     * @mbggenerated
     */
    public Integer getSubjid() {
        return subjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column markrecord.subjID
     *
     * @param subjid the value for markrecord.subjID
     *
     * @mbggenerated
     */
    public void setSubjid(Integer subjid) {
        this.subjid = subjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column markrecord.practiScore
     *
     * @return the value of markrecord.practiScore
     *
     * @mbggenerated
     */
    public Float getPractiscore() {
        return practiscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column markrecord.practiScore
     *
     * @param practiscore the value for markrecord.practiScore
     *
     * @mbggenerated
     */
    public void setPractiscore(Float practiscore) {
        this.practiscore = practiscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column markrecord.theoryScore
     *
     * @return the value of markrecord.theoryScore
     *
     * @mbggenerated
     */
    public Float getTheoryscore() {
        return theoryscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column markrecord.theoryScore
     *
     * @param theoryscore the value for markrecord.theoryScore
     *
     * @mbggenerated
     */
    public void setTheoryscore(Float theoryscore) {
        this.theoryscore = theoryscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column markrecord.diffiScore
     *
     * @return the value of markrecord.diffiScore
     *
     * @mbggenerated
     */
    public Float getDiffiscore() {
        return diffiscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column markrecord.diffiScore
     *
     * @param diffiscore the value for markrecord.diffiScore
     *
     * @mbggenerated
     */
    public void setDiffiscore(Float diffiscore) {
        this.diffiscore = diffiscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column markrecord.comUID
     *
     * @return the value of markrecord.comUID
     *
     * @mbggenerated
     */
    public Integer getComuid() {
        return comuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column markrecord.comUID
     *
     * @param comuid the value for markrecord.comUID
     *
     * @mbggenerated
     */
    public void setComuid(Integer comuid) {
        this.comuid = comuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column markrecord.lastTime
     *
     * @return the value of markrecord.lastTime
     *
     * @mbggenerated
     */
    public Date getLasttime() {
        return lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column markrecord.lastTime
     *
     * @param lasttime the value for markrecord.lastTime
     *
     * @mbggenerated
     */
    public void setLasttime(Date lasttime) {
        this.lasttime = lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column markrecord.comment
     *
     * @return the value of markrecord.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column markrecord.comment
     *
     * @param comment the value for markrecord.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Markrecord other = (Markrecord) that;
        return (this.getRid() == null ? other.getRid() == null : this.getRid().equals(other.getRid()))
            && (this.getSubjid() == null ? other.getSubjid() == null : this.getSubjid().equals(other.getSubjid()))
            && (this.getPractiscore() == null ? other.getPractiscore() == null : this.getPractiscore().equals(other.getPractiscore()))
            && (this.getTheoryscore() == null ? other.getTheoryscore() == null : this.getTheoryscore().equals(other.getTheoryscore()))
            && (this.getDiffiscore() == null ? other.getDiffiscore() == null : this.getDiffiscore().equals(other.getDiffiscore()))
            && (this.getComuid() == null ? other.getComuid() == null : this.getComuid().equals(other.getComuid()))
            && (this.getLasttime() == null ? other.getLasttime() == null : this.getLasttime().equals(other.getLasttime()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRid() == null) ? 0 : getRid().hashCode());
        result = prime * result + ((getSubjid() == null) ? 0 : getSubjid().hashCode());
        result = prime * result + ((getPractiscore() == null) ? 0 : getPractiscore().hashCode());
        result = prime * result + ((getTheoryscore() == null) ? 0 : getTheoryscore().hashCode());
        result = prime * result + ((getDiffiscore() == null) ? 0 : getDiffiscore().hashCode());
        result = prime * result + ((getComuid() == null) ? 0 : getComuid().hashCode());
        result = prime * result + ((getLasttime() == null) ? 0 : getLasttime().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", subjid=").append(subjid);
        sb.append(", practiscore=").append(practiscore);
        sb.append(", theoryscore=").append(theoryscore);
        sb.append(", diffiscore=").append(diffiscore);
        sb.append(", comuid=").append(comuid);
        sb.append(", lasttime=").append(lasttime);
        sb.append(", comment=").append(comment);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}