package com.backend.Dao;

import com.backend.Domain.Markrecord;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface MarkrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int insert(Markrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int insertSelective(Markrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    Markrecord selectByPrimaryKey(Integer rid);

    @Select("select * from markrecord where subjID=#{sid} order by lasttime desc")
    List<Markrecord> selectBySubjId(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Markrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Markrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Markrecord record);
}