package com.backend.Dao;

import com.backend.Domain.Markrecord;

public interface MarkrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int insert(Markrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int insertSelective(Markrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    Markrecord selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Markrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Markrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table markrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Markrecord record);
}